name: edit game
description: request to edit/fix game
title: 'Edit: '
labels: ['report link']

body:
  - type: input
    attributes:
      label: new game URL
      description: new link to the game
      placeholder: 'https://23apples.gg/run3'

  
  - type: input
    attributes:
      label: game name
      description: "name of the game"
      placeholder: 'Run 3'
